import type { Tool, Article, Stack, Author, Review } from './types'

export const authors: Author[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    avatar: '/avatars/sarah.jpg',
    role: 'AI Tools Editor',
    bio: 'Former product manager at Notion. Now writing about the tools that power modern work.',
  },
  {
    id: '2',
    name: 'Emeka Okonkwo',
    avatar: '/avatars/emeka.jpg',
    role: 'SaaS Analyst',
    bio: 'Building and writing about SaaS from Lagos. Focus on Africa-friendly tools.',
  },
  {
    id: '3',
    name: 'Alex Rivera',
    avatar: '/avatars/alex.jpg',
    role: 'Automation Expert',
    bio: 'Zapier certified expert. Helping teams automate boring work since 2019.',
  },
  {
    id: '4',
    name: 'Maya Patel',
    avatar: '/avatars/maya.jpg',
    role: 'Design Tools Lead',
    bio: 'Designer turned writer. Covering AI design tools and creative workflows.',
  },
]

export const tools: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT Pro',
    slug: 'chatgpt-pro',
    description: 'ChatGPT Pro is OpenAIs flagship conversational AI. It excels at writing, code generation, analysis tasks, and multimodal understanding. With GPT-4o, it can process text, images, and files with a 128K context window.',
    shortDescription: 'AI-powered writing, coding, and analysis assistant by OpenAI',
    logo: '/tools/chatgpt.svg',
    category: 'writing',
    subcategories: ['coding', 'analysis', 'research'],
    pricing: {
      hasFree: true,
      freeDescription: 'Limited GPT-3.5 access with rate limits',
      plans: [
        { name: 'Free', price: '$0', period: 'month', features: ['GPT-3.5 access', 'Basic usage', 'Rate limited'] },
        { name: 'Pro', price: '$20', period: 'month', features: ['GPT-4o access', 'DALL-E 3', 'Plugins', 'Priority access'] },
        { name: 'Team', price: '$25', period: 'month', features: ['Everything in Pro', 'Admin console', 'Team analytics', 'SSO'] },
      ],
    },
    rating: 4.8,
    reviewCount: 2412,
    badges: ['free', 'pro', 'africa-friendly', 'trending'],
    integrations: ['Zapier', 'Make', 'API'],
    platforms: ['Web', 'iOS', 'Android', 'API'],
    website: 'https://chat.openai.com',
    africaFriendly: true,
    bestFor: ['Writers', 'Developers', 'Researchers', 'Content creators'],
    pros: ['Excellent at long-form writing', 'Strong code understanding', 'Multimodal capabilities', 'Large context window (128K)'],
    cons: ['Can hallucinate facts', 'Requires good prompting skills', 'Rate limits on free tier'],
    lastUpdated: '2026-03-15',
  },
  {
    id: '2',
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'Midjourney is an AI art generator that creates stunning images from text prompts. Known for its artistic, aesthetic quality and photorealistic capabilities.',
    shortDescription: 'AI image generation with artistic, photorealistic quality',
    logo: '/tools/midjourney.svg',
    category: 'design',
    subcategories: ['image-generation', 'art', 'creative'],
    pricing: {
      hasFree: false,
      plans: [
        { name: 'Basic', price: '$10', period: 'month', features: ['200 images/month', 'General commercial terms'] },
        { name: 'Standard', price: '$30', period: 'month', features: ['15 hours fast GPU', 'Unlimited relaxed GPU'] },
        { name: 'Pro', price: '$60', period: 'month', features: ['30 hours fast GPU', 'Stealth mode'] },
      ],
    },
    rating: 4.9,
    reviewCount: 1834,
    badges: ['pro', 'trending', 'editor-pick'],
    integrations: ['Discord'],
    platforms: ['Discord', 'Web'],
    website: 'https://midjourney.com',
    africaFriendly: false,
    bestFor: ['Designers', 'Artists', 'Marketing teams', 'Content creators'],
    pros: ['Best-in-class image quality', 'Strong artistic style', 'Active community', 'Regular updates'],
    cons: ['No free tier', 'Discord-only interface', 'Learning curve for prompts'],
    lastUpdated: '2026-03-10',
  },
  {
    id: '3',
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'Notion AI is an AI assistant built into Notion that helps with writing, summarizing, brainstorming, and organizing your workspace.',
    shortDescription: 'AI-powered productivity assistant within Notion',
    logo: '/tools/notion.svg',
    category: 'productivity',
    subcategories: ['writing', 'organization', 'project-management'],
    pricing: {
      hasFree: false,
      plans: [
        { name: 'AI Add-on', price: '$10', period: 'month', features: ['Unlimited AI responses', 'Works with all Notion plans'] },
      ],
    },
    rating: 4.5,
    reviewCount: 1256,
    badges: ['pro', 'africa-friendly'],
    integrations: ['Slack', 'Google Drive', 'Figma', 'GitHub'],
    platforms: ['Web', 'Desktop', 'iOS', 'Android'],
    website: 'https://notion.so/ai',
    africaFriendly: true,
    bestFor: ['Teams', 'Project managers', 'Writers', 'Students'],
    pros: ['Seamless Notion integration', 'Great for documentation', 'Team collaboration', 'Template library'],
    cons: ['Requires Notion subscription', 'Limited compared to ChatGPT', 'Can be slow'],
    lastUpdated: '2026-03-12',
  },
  {
    id: '4',
    name: 'Zapier',
    slug: 'zapier',
    description: 'Zapier connects your apps and automates workflows with no code. Build automated workflows called Zaps to move data between apps.',
    shortDescription: 'No-code automation connecting 5000+ apps',
    logo: '/tools/zapier.svg',
    category: 'automation',
    subcategories: ['integration', 'workflow', 'no-code'],
    pricing: {
      hasFree: true,
      freeDescription: '100 tasks/month, 5 Zaps',
      plans: [
        { name: 'Free', price: '$0', period: 'month', features: ['100 tasks/month', '5 Zaps', 'Single-step Zaps'] },
        { name: 'Starter', price: '$19.99', period: 'month', features: ['750 tasks/month', '20 Zaps', 'Multi-step Zaps'] },
        { name: 'Professional', price: '$49', period: 'month', features: ['2000 tasks/month', 'Unlimited Zaps', 'Paths'] },
      ],
    },
    rating: 4.6,
    reviewCount: 3421,
    badges: ['free', 'pro', 'no-code', 'africa-friendly'],
    integrations: ['5000+ apps'],
    platforms: ['Web'],
    website: 'https://zapier.com',
    africaFriendly: true,
    bestFor: ['Teams', 'Freelancers', 'Small businesses', 'Marketers'],
    pros: ['Massive app library', 'No code required', 'Reliable', 'Great support'],
    cons: ['Can get expensive', 'Complex workflows need expertise', 'Task limits'],
    lastUpdated: '2026-03-14',
  },
  {
    id: '5',
    name: 'Jasper AI',
    slug: 'jasper-ai',
    description: 'Jasper is an AI writing assistant designed for marketing teams. Create blog posts, social media content, ads, and more.',
    shortDescription: 'AI copywriting for marketing and brand content',
    logo: '/tools/jasper.svg',
    category: 'marketing',
    subcategories: ['copywriting', 'content', 'seo'],
    pricing: {
      hasFree: true,
      freeDescription: '7-day free trial',
      plans: [
        { name: 'Creator', price: '$49', period: 'month', features: ['Unlimited words', '50+ templates', 'Brand voice'] },
        { name: 'Teams', price: '$125', period: 'month', features: ['Everything in Creator', 'Team collaboration', 'Custom workflows'] },
      ],
    },
    rating: 4.4,
    reviewCount: 892,
    badges: ['pro', 'trending'],
    integrations: ['Surfer SEO', 'Grammarly', 'Chrome'],
    platforms: ['Web', 'Chrome extension'],
    website: 'https://jasper.ai',
    africaFriendly: false,
    bestFor: ['Marketing teams', 'Content agencies', 'E-commerce'],
    pros: ['Marketing-focused templates', 'Brand voice training', 'SEO integration'],
    cons: ['Expensive', 'Overkill for simple tasks', 'Learning curve'],
    lastUpdated: '2026-03-08',
  },
  {
    id: '6',
    name: 'Runway ML',
    slug: 'runway-ml',
    description: 'Runway is an AI-powered creative suite for video editing, generation, and visual effects.',
    shortDescription: 'AI video generation and editing platform',
    logo: '/tools/runway.svg',
    category: 'video',
    subcategories: ['video-editing', 'generation', 'vfx'],
    pricing: {
      hasFree: true,
      freeDescription: '125 credits for new users',
      plans: [
        { name: 'Standard', price: '$15', period: 'month', features: ['625 credits/month', 'Gen-2 video'] },
        { name: 'Pro', price: '$35', period: 'month', features: ['2250 credits/month', 'Priority rendering'] },
      ],
    },
    rating: 4.7,
    reviewCount: 678,
    badges: ['free', 'pro', 'trending', 'new'],
    integrations: ['After Effects', 'Premiere'],
    platforms: ['Web', 'iOS'],
    website: 'https://runwayml.com',
    africaFriendly: true,
    bestFor: ['Video editors', 'Content creators', 'Filmmakers'],
    pros: ['Industry-leading video AI', 'Easy to use', 'Quick iterations'],
    cons: ['Credit-based pricing', 'Quality varies', 'Render times'],
    lastUpdated: '2026-03-16',
  },
  {
    id: '7',
    name: 'Claude',
    slug: 'claude',
    description: 'Claude is Anthropics AI assistant, known for nuanced analysis, long context, and helpful, harmless responses.',
    shortDescription: 'Thoughtful AI assistant for complex analysis',
    logo: '/tools/claude.svg',
    category: 'writing',
    subcategories: ['analysis', 'coding', 'research'],
    pricing: {
      hasFree: true,
      freeDescription: 'Limited daily usage',
      plans: [
        { name: 'Pro', price: '$20', period: 'month', features: ['5x more usage', 'Claude 3 Opus', 'Priority access'] },
        { name: 'Team', price: '$25', period: 'month', features: ['Everything in Pro', 'Admin tools', 'Central billing'] },
      ],
    },
    rating: 4.7,
    reviewCount: 1543,
    badges: ['free', 'pro', 'africa-friendly', 'editor-pick'],
    integrations: ['API', 'Slack'],
    platforms: ['Web', 'iOS', 'API'],
    website: 'https://claude.ai',
    africaFriendly: true,
    bestFor: ['Researchers', 'Analysts', 'Writers', 'Developers'],
    pros: ['200K context window', 'Nuanced responses', 'Strong ethics', 'Great at analysis'],
    cons: ['Slower than GPT-4', 'More cautious responses', 'Limited integrations'],
    lastUpdated: '2026-03-15',
  },
  {
    id: '8',
    name: 'Canva',
    slug: 'canva',
    description: 'Canva is a design platform with AI-powered features for creating graphics, presentations, and videos.',
    shortDescription: 'AI-enhanced design platform for everyone',
    logo: '/tools/canva.svg',
    category: 'design',
    subcategories: ['graphics', 'presentation', 'social-media'],
    pricing: {
      hasFree: true,
      freeDescription: 'Free forever with limited features',
      plans: [
        { name: 'Free', price: '$0', period: 'month', features: ['250K templates', 'Basic AI features', '5GB storage'] },
        { name: 'Pro', price: '$12.99', period: 'month', features: ['All templates', 'Magic Write AI', '1TB storage'] },
        { name: 'Teams', price: '$14.99', period: 'month', features: ['Everything in Pro', 'Brand kit', 'Team folders'] },
      ],
    },
    rating: 4.8,
    reviewCount: 5678,
    badges: ['free', 'pro', 'africa-friendly', 'no-code'],
    integrations: ['Google Drive', 'Dropbox', 'Social platforms'],
    platforms: ['Web', 'Desktop', 'iOS', 'Android'],
    website: 'https://canva.com',
    africaFriendly: true,
    bestFor: ['Non-designers', 'Social media managers', 'Small businesses', 'Students'],
    pros: ['Easy to use', 'Huge template library', 'Generous free tier', 'AI image generation'],
    cons: ['Limited for complex designs', 'Watermarks on some free content', 'Export limitations'],
    lastUpdated: '2026-03-14',
  },
]

export const articles: Article[] = [
  {
    id: '1',
    slug: '10-ai-writing-tools-2026',
    title: '10 AI Writing Tools That Actually Save You Time in 2026',
    excerpt: 'A deep dive into the tools that content teams, freelancers, and marketers are using right now to produce better content faster.',
    content: '',
    featuredImage: '/articles/ai-writing-tools.jpg',
    author: authors[0],
    publishedAt: '2026-03-15',
    updatedAt: '2026-03-18',
    readTime: 12,
    category: 'ai-tools',
    tags: ['writing', 'productivity', 'content-creation'],
    targetRoles: ['freelancer', 'agency', 'saas-founder'],
    viewCount: 2400,
    featured: true,
    toolsCompared: [tools[0], tools[4], tools[6]],
  },
  {
    id: '2',
    slug: 'saas-pricing-strategies-ai-era',
    title: 'Why SaaS Pricing is Changing in the AI Era',
    excerpt: 'Credits, tokens, and usage-based pricing are replacing simple subscriptions. Heres what founders need to know.',
    content: '',
    featuredImage: '/articles/saas-pricing.jpg',
    author: authors[1],
    publishedAt: '2026-03-12',
    updatedAt: '2026-03-12',
    readTime: 8,
    category: 'saas-news',
    tags: ['pricing', 'business-model', 'founders'],
    targetRoles: ['saas-founder'],
    viewCount: 1850,
    featured: true,
  },
  {
    id: '3',
    slug: 'automate-client-onboarding-zapier',
    title: 'How to Automate Client Onboarding with Zapier (Step-by-Step)',
    excerpt: 'Save 5+ hours per week by automating your client onboarding. Complete tutorial with templates included.',
    content: '',
    featuredImage: '/articles/automation-zapier.jpg',
    author: authors[2],
    publishedAt: '2026-03-10',
    updatedAt: '2026-03-10',
    readTime: 15,
    category: 'tutorials',
    tags: ['automation', 'zapier', 'agency'],
    targetRoles: ['freelancer', 'agency'],
    viewCount: 3200,
    featured: false,
  },
  {
    id: '4',
    slug: 'ai-design-tools-comparison-2026',
    title: 'Midjourney vs DALL-E vs Stable Diffusion: The Complete Comparison',
    excerpt: 'Which AI image generator is right for your workflow? We tested all three with real design projects.',
    content: '',
    featuredImage: '/articles/ai-design-comparison.jpg',
    author: authors[3],
    publishedAt: '2026-03-08',
    updatedAt: '2026-03-14',
    readTime: 18,
    category: 'comparisons',
    tags: ['design', 'image-generation', 'comparison'],
    targetRoles: ['freelancer', 'agency'],
    viewCount: 4100,
    featured: true,
    toolsCompared: [tools[1], tools[7]],
  },
  {
    id: '5',
    slug: 'africa-friendly-ai-tools',
    title: 'The Best AI Tools for African Freelancers and Businesses',
    excerpt: 'Tools with accessible pricing, mobile-friendly interfaces, and payment options that work in Africa.',
    content: '',
    featuredImage: '/articles/africa-ai-tools.jpg',
    author: authors[1],
    publishedAt: '2026-03-05',
    updatedAt: '2026-03-05',
    readTime: 10,
    category: 'ai-tools',
    tags: ['africa', 'freelancer', 'accessibility'],
    targetRoles: ['freelancer'],
    viewCount: 2800,
    featured: false,
  },
  {
    id: '6',
    slug: 'building-saas-ai-2026',
    title: 'How to Build a SaaS Product with AI in 2026 (No-Code Guide)',
    excerpt: 'From idea to launch: use AI tools to build, market, and scale your SaaS without writing code.',
    content: '',
    featuredImage: '/articles/saas-ai-build.jpg',
    author: authors[0],
    publishedAt: '2026-03-02',
    updatedAt: '2026-03-02',
    readTime: 20,
    category: 'tutorials',
    tags: ['saas', 'no-code', 'founders', 'ai'],
    targetRoles: ['saas-founder'],
    viewCount: 5600,
    featured: false,
  },
]

export const stacks: Stack[] = [
  {
    id: '1',
    slug: 'content-creator-pro',
    name: 'Content Creator Pro Stack',
    description: 'The ultimate stack for content teams and solo creators. Write, design, and distribute content faster.',
    tools: [tools[0], tools[2], tools[1], tools[5], tools[3]],
    creator: authors[0],
    targetRole: 'freelancer',
    category: 'content',
    cloneCount: 1234,
    rating: 4.9,
    createdAt: '2026-02-15',
    updatedAt: '2026-03-10',
    featured: true,
  },
  {
    id: '2',
    slug: 'agency-operations',
    name: 'Agency Operations Stack',
    description: 'Run your agency on autopilot with these 7 essential tools. From client management to delivery.',
    tools: [tools[2], tools[3], tools[7]],
    creator: authors[2],
    targetRole: 'agency',
    category: 'operations',
    cloneCount: 892,
    rating: 4.7,
    createdAt: '2026-01-20',
    updatedAt: '2026-03-05',
    featured: true,
  },
  {
    id: '3',
    slug: 'saas-founder-bootstrap',
    name: 'SaaS Founder Bootstrap Stack',
    description: 'Ship your MVP with $0 budget using these free and affordable tools. Perfect for bootstrappers.',
    tools: [tools[0], tools[6], tools[3]],
    creator: authors[1],
    targetRole: 'saas-founder',
    category: 'startup',
    cloneCount: 756,
    rating: 4.8,
    createdAt: '2026-02-01',
    updatedAt: '2026-03-12',
    featured: true,
  },
  {
    id: '4',
    slug: 'solo-freelancer',
    name: 'Solo Freelancer Stack',
    description: 'Everything you need to run a one-person business. Simple, affordable, effective.',
    tools: [tools[0], tools[7], tools[3]],
    creator: authors[1],
    targetRole: 'freelancer',
    category: 'productivity',
    cloneCount: 432,
    rating: 4.6,
    createdAt: '2026-02-10',
    updatedAt: '2026-03-01',
    featured: false,
  },
  {
    id: '5',
    slug: 'design-team',
    name: 'Design Team Stack',
    description: 'Collaborative design workflow for remote creative teams. AI-powered design at scale.',
    tools: [tools[1], tools[7], tools[2]],
    creator: authors[3],
    targetRole: 'agency',
    category: 'design',
    cloneCount: 287,
    rating: 4.5,
    createdAt: '2026-01-25',
    updatedAt: '2026-02-28',
    featured: false,
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    userId: '101',
    userName: 'Chidi A.',
    userAvatar: '/avatars/user1.jpg',
    verified: true,
    rating: 5,
    content: 'Game-changer for my freelance writing. The Pro plan is worth every dollar, especially with the new features.',
    upvotes: 34,
    downvotes: 2,
    createdAt: '2026-03-10',
    location: 'Nigeria',
  },
  {
    id: '2',
    userId: '102',
    userName: 'Maria S.',
    userAvatar: '/avatars/user2.jpg',
    verified: true,
    rating: 4,
    content: 'Great for quick drafts and brainstorming. Sometimes needs editing but saves hours overall.',
    upvotes: 22,
    downvotes: 1,
    createdAt: '2026-03-08',
    location: 'Spain',
  },
  {
    id: '3',
    userId: '103',
    userName: 'James K.',
    userAvatar: '/avatars/user3.jpg',
    verified: false,
    rating: 5,
    content: 'Best AI tool I have used for coding. The code explanation feature is incredibly helpful.',
    upvotes: 18,
    downvotes: 0,
    createdAt: '2026-03-05',
  },
]

export const toolCategories = [
  { id: 'writing', name: 'Writing', icon: 'pen-tool', count: 24 },
  { id: 'design', name: 'Design', icon: 'palette', count: 18 },
  { id: 'code', name: 'Code', icon: 'code', count: 15 },
  { id: 'video', name: 'Video', icon: 'video', count: 12 },
  { id: 'audio', name: 'Audio', icon: 'mic', count: 8 },
  { id: 'data', name: 'Data', icon: 'database', count: 10 },
  { id: 'automation', name: 'Automation', icon: 'zap', count: 14 },
  { id: 'productivity', name: 'Productivity', icon: 'layout', count: 20 },
]
